---

- name: make a dir
  file:
    path: "{{ item }}"
    state: "{{ dir_state }}"
    owner: "{{ gitlab_owner }}"
    group: "{{ gitlab_group }}"
    mode: "{{ gitlab_mod }}"
  loop: "{{ gitlab_directory }}"