---

- name: install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  loop: "{{ required_packages }}"

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ item.gpg_url }}"
    state: "{{ item.state }}"
  loop: "{{ docker }}"

- name: Add Docker Repository
  apt_repository:
    repo: "{{ item.repository_url }}"
    state: "{{ item.state }}"
  loop: "{{ docker }}"

- name: install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker_packages }}"

- name: install pip packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ pip_packages }}"

- name: install docker-compose
  get_url:
    url: "{{ item.compose_url }}"
    dest: "{{ item.compose_dir }}/docker-compose"
    mode: a+x
  loop: "{{ docker }}"
