---

docker_url: https://download.docker.com/linux/ubuntu
package_state: present
os_type: "{{ ansible_system | default('Linux')}}"
os_architecture: "{{ ansible_architecture | default('x86_64') }}"
gitlab_config_dir:  /opt/gitlab/config

pip_packages:
  - docker
  - docker-compose

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

required_packages:
  - aptitude
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools

docker:
  - name: common
    gpg_url: "{{ docker_url }}/gpg"
    repository_url: "deb [arch=amd64] {{ docker_url }} focal stable"
    state: "{{ package_state }}"
    compose_url: "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-{{ os_type }}-{{ os_architecture }}"
    compose_dir: /usr/local/bin
