---

- name: make a dir for elastic
  file:
    path: "{{ item.dir }}"
    state: "{{ item.state }}"
  loop: "{{ elastic }}"

- name: make a dir for elastic
  file:
    path: "{{ item.data }}"
    state: "{{ item.state }}"
  loop: "{{ elastic }}"

