---

gitlab_owner: root
gitlab_group: root
gitlab_mod: 0755
server_dns_name: 192.168.42.223
gitlab_config_dir: /opt/gitlab/config
dir_state: directory

gitlab_directory:
  - /opt/gitlab
  - "{{ gitlab_config_dir }}"
  - /opt/gitlab/logs
  - /opt/gitlab/data
  - /opt/gitlab-runner
  - /opt/gitlab-runner/config
  - /opt/gitlab-runner/data